### ISSUE TITLE
Smart Highlighter : Color / Click / Menu

### ISSUE THREAD

**Issue by morbak** [sieukrem/jn-npp-plugin#75]
Is it possible to change the color of the highlight line result in the scroll bar? 
Will it be possilbe to automatically scroll/jump on the concerned text area when we click on the highlight line result in the scroll bar? 

Is it possible to load only the Smart Highlighter functionality? becasue lot of other menus was added?

**Comment by sieukrem** [comment]
> Is it possible to change the color of the highlight line result in the scroll bar?

Yes! You can only use predefined colors for Styling Tokens accessible via dropdown menu on any selection.
Due to change the color
1. Open <you path>\npp\plugins\jN\jN\includes\SmartHighlighter.js
2. Replace MARKALLEXT5 by e.g. MARKALLEXT4 
3. Restart Npp

>Will it be possilbe to automatically scroll/jump on the concerned text area when we click on the highlight line result in the scroll bar?

No! I thought about this feature, but it is difficult to get it presize on middle big files

>Is it possible to load only the Smart Highlighter functionality? becasue lot of other menus was added?

Yes!
1. Navigate to <you path>\npp\plugins\jN\jN\includes\ in Windows Explorer
2. Move all of files in disabled directory, but MenuCmds.js, Dialog.js and SmartHighlighter.js
3. Restart Npp
