### ISSUE TITLE
Smart Highlighter Not working on Double Click

### ISSUE THREAD

**Issue by mlcrow** [sieukrem/jn-npp-plugin#76]
After updating npp to v7.7, smart highlighter has stopped functioning correctly. If I double click to select a word, smarthightlighter does not show it's other locations in the scroll bar. I am able to bring them up if I select the word, and run the smarthighlighter.js separately.

**Comment by sieukrem** [comment]
Please check Npp setting about selection optimization. I don't remember the name of setting now!

**Comment by mlcrow** [comment]
I'm not seeing a selection optimization setting anywhere.

**Comment by mlcrow** [comment]
I've reverted to npp v7.6.6 and this has resolved the issue.

**Comment by kobbe** [comment]
Same problem for me

**Comment by sieukrem** [comment]
The feature works in my environment
Win10
Notepad++ v7.7 x86

**Comment by frmadiot** [comment]
Hi !
Don't work for mee too !
win7
Notepad++ v7.8.1 64b

**Comment by sieukrem** [comment]
Is the word you are clicking on selected afterwards?
Are other locations of the word highlighted?

**Comment by frmadiot** [comment]
on doubleclick on word: word is selected, all words patterns inside the file are selected,the selection highlights in the scrollbar is not working.

after unistallation of jn++ plugin : same behavior

**Comment by AakaFosfor** [comment]
Same problem here.

Notepad++ v7.8.4   (64-bit)
Build time : Jan 29 2020 - 01:31:03
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1709
OS Build : 16299.1686
Plugins : CodeAlignmentNpp.dll DSpellCheck.dll Explorer.dll jN.dll mimeTools.dll NppConverter.dll NppExec.dll NppExport.dll NPPJSONViewer.dll NppMarkdownPanel.dll NppSaveAsAdmin.dll zoomdisabler_x64.dll

The problem seems to be that the vertical highlighting bar (next to the scrollbar) seems to be updated only when switching between documents.

**Comment by sieukrem** [comment]
I assume that some messages are either not sent or not routed to the plugin.
Can you please try to run Npp with only JN enabled, uninstall other plugins !

**Comment by Nolenz** [comment]
With JN as my only plugin in Notepad++ v7.8.4 64-bit, I can confirm the smart highlight is not working properly. It works in v7.6.6 64-bit, but not in v7.8.4 64-bit.

However, it seems to work perfectly fine in 7.8.4 **32-bit**.

**Comment by sieukrem** [comment]
@Nolenz  Thank you for the x64 hint. This issue is related to the [breaking change](https://community.notepad-plus-plus.org/topic/17755/notepad-7-7-breaking-change-of-scnotification-definition-in-x64-build).

**Comment by AakaFosfor** [comment]
It works for me.
Thanks a bunch!
