### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by WinterSilence** [sieukrem/jn-npp-plugin#93]
1. I found easy solution to emulate `console.log()` -[ `JSON.stringify(var);` ](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify), maybe with [codemirror](https://codemirror.net/demo/folding.html) and display result in bottom dock, as example:
~~~
class Console {
    constructor(config) {
        this.id = 'jn-console';
        // only for examlple - need rewrite Dialog.js
        let defaultConfig = {
            dockable: true,
            // css: 'body {overflow:scroll;background:#fff;color:#000;font-size:90%;font-family:Menlo,monospace;}',
            html: '<ol id="' + this.id + '"></ol>',
            name: 'JN console',
            docking: 'bottom'
        };
        this.dock = new Dialog(Object.assign(defaultConfig, config));
    }
    show() {
        this.dock.visible = true;
        // call by chain
        return this;
    }
    hide() {
        this.dock.visible = false;
        return this;
    }
    isVisible: function () {
        return this.dock && this.dock.visible;
    }
    writeLn(str) {
        str = '<li>' + (typeof str == 'String' ? str : JSON.stringify(str)) + '</li>';
        this.dock.document.getElementById(this.id).insertAdjacentHTML('beforeend', str);
    }
    clear{
        this.dock.document.getElementById(this.id).innerHTML = '';
    }
    dump(...data) {
        // @todo highlight + code folding https://codemirror.net/demo/folding.html
        return JSON.stringify(data.length == 1 ? data[0] : data);
    }
    /**
     * @param {string} command Path to CLI application or command.
     * @param {object} longArgs An array of long option/value pairs (without prefix `--`).
     * @param {object} shortArgs An array of short option/value pairs (without prefix `-`).
     */
    execute(command, longArgs = {}, shortArgs = {}) {
        Object.entries(longArgs).forEach(function (opt, value) {
            command += ' --' + opt + ' ' + JSON.stringify(value);
        });
        Object.entries(shortArgs).forEach(function (opt, value) {
            command += ' -' + opt + ' ' + JSON.stringify(value);
        });
        try {
            if (! this.shell) {
                this.shell = new ActiveXObject('WScript.Shell');
            }
            let scriptExec = this.shell.Exec(command);
            let error = scriptExec.StdErr.ReadAll();
            if (error) {
                throw new EvalError(error);
            }
            // append '' for fix wrong type at empty result
            return scriptExec.StdOut.ReadAll() + '';
        } catch (e) {
            this.writeLn('<mark>' + this.dump(e) + '</mark>');
            return false;
        }
    }
}
~~~

2,  `FS` class wrap [`FileSystemObject`](https://www.script-coding.com/WSH/FileSystemObject.html) methods

>  debug was useful at the beginning as there was no VS Debugger Support

VS Debugger can explore dll content?!

**Comment by WinterSilence** [comment]
3. need require lodash or something like this - after php write on js so hard.

**Comment by sieukrem** [comment]
Good start 😄 
Precise the Title and Description of the issue. 

* Title is like an emails title should help to find and separate this issue from other issue in the list of issues.
* In the description you argue for the the issue. I use following schema
   * Observation
   * Expectation
   * Wish

Im am sure there are much better tutorials "how to write perfect issue?" on the internet (e.g. [Writing-Good-Feature-Requests](https://github.com/rstudio/rstudio/wiki/Writing-Good-Feature-Requests)).

**Comment by sieukrem** [comment]
>VS Debugger can explore dll content?!

What do you mean? I meant that you can [debug your javascript](../wiki/Debugging) running in Npp by attaching to it from Visual Studio.

**Comment by WinterSilence** [comment]
> Precise the Title and Description of the issue

it's common discuss & small project

> What do you mean

I mean, debugger can inspect Library instance created as `new Library("User32.dll");` or  `new ActiveXObject("Shell.Application")`? 

But you leaved main theme this issue - I be glad to help you with JS refactoring.
P.S. look at yourself before teaching someone - I didn't use some coding/doc style because you do don't have it - read about `.gitbub/ISSUE_TEMPLATE`

**Comment by sieukrem** [comment]
OK let us discuss!

> I mean, debugger can inspect Library instance created as new Library("User32.dll"); or new ActiveXObject("Shell.Application")?

Yes, the debugger allows to inspect and modify properties of instances.

> But you leaved main theme this issue - I be glad to help you with JS refactoring.
Maybe because I did not understand the content of the issue description. Let me summarize what I understand from the description.
* You found a solution for not introduced problem (I assume you meant console.log could not print out string representation of complex objects like array or object)
* You refer to codemirror which seems to be an code editor for browser. I assume that you meant the folding solution for log entries of console
* The code of class Console is not about console.log or codemirror, but about Terminal
* If I understand it correctly, then we could create 2 feature requests. One for Terminal and another for Console.


> P.S. look at yourself before teaching someone - I didn't use some coding/doc style because you do don't have it - read about .gitbub/ISSUE_TEMPLATE

Nobody is perfect. ;-) Please don't judge, english is my third language. It was never my intention to teach you or to be unpolite. It was a try to shorten the mail ping pong by giving you the opportunity to do the best by you self if I let you know what are quality properties.

You are right there is no issue template or contribution rules. It was not werth to setup them if I was alone. Rules are very important as soon as there are more contributors. They prevent misunderstandings.

**Comment by WinterSilence** [comment]
> I assume you meant console.log could not print out string representation of complex objects like array or object

[console.log()](https://developer.mozilla.org/en-US/docs/Web/API/Console/log)

**Comment by WinterSilence** [comment]
@sieukrem
> If I understand it correctly, then we could create 2 feature requests. One for Terminal and another for Console.

class with one method(Terminal) look like strange + it's confuse users. as you say, when project grow up then code grow up too. I vote to solutions based on OOP, but focused on handy scripting with easy debug and created for np++ users junior(need basic js to start), it's similar to [greacemonkey](https://www.tampermonkey.net).

**Comment by sieukrem** [comment]
From the perspective of design principles (e.g [Interface Segregation Principle](https://en.wikipedia.org/wiki/Interface_segregation_principle) it is fully OK to have two abstractions instead of one. OOP is only a tool to satisfy such design principles by implementing several design patterns.

But back to the features you want to implement.

Terminal - the window at the bottom of application allowing to input commands, execute them asyncrously to the n++ and printing the stderr and stdout of the program appending it at the end.
Terminal is used primary by end user of n++, who is writing or reading text or shell scrips.

Console.log() - the possibility for javascript developer to print context relevant information from every place in code which he wants to investigate. It provides a simple debugging possibility. This tool is only important at the development time of javascripts  for n++. The browser way to printout the result of conlsole.log() is the Developer Window. In the Nodejs it is the stdout or stderr.

There is no need to implement the terminal and console in one class.

**Comment by WinterSilence** [comment]
@sieukrem > Terminal - the window at the bottom of application allowing to input commands, execute them asyncrously to the n++ and printing the stderr and stdout of the program appending it at the end.

no, no, no a talk about debug console without emulation real terminal. I want easy tools for handy scripting without external tools as VS. Something similar to [Greasemonkey](https://en.wikipedia.org/wiki/Greasemonkey), try create script in it - light editor with [hightlight code and linter](https://ace.c9.io) + some helpers to fast coding.

**Comment by sieukrem** [comment]
The conversation stopped!
